name: Check Vulnerabilities

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-vuln:
    name: Vuln Checkout
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v2.4.2

      - name: Grype
        uses: anchore/scan-action/download-grype@v3
        id: grype
      - name : Store
        run: ${{steps.grype.outputs.cmd}} -o json dir:. > grypetmp.json
      
      - name: Syft
        uses: anchore/sbom-action/download-syft@v0
        id: syft
      - name: Store
        run: ${{ steps.syft.outputs.cmd }} -o json dir:. > syfttmp.json

      