name: Check Vulnerabilities

on:
  push:
    branches:
      main
  workflow_dispatch:

jobs:

  ## Récupère les vulnérabilités liées aux dépendances
  Run-Grype:
    name: Grype Summary
    runs-on: ubuntu-latest
      
    steps:
      - name : Checkout
        uses : actions/checkout@v4

      - name: Retrieving Grype
        uses: anchore/scan-action/download-grype@v3.6.4
        id: grype
      - name : Store
        run: ${{steps.grype.outputs.cmd}} -o json dir:. > grypetmp.json

      - name: Upload Grype Summary
        uses: actions/upload-artifact@v4.3.1
        with:
          name: grype_summary
          path: grypetmp.json
  
  ## Récupère les dépendances (nb totale)
  Run-Syft:
    name: Syft Summary
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v4

      - name: Retrieving Syft
        uses: anchore/sbom-action/download-syft@v0.15.10
        id: syft
      - name: Store
        run: ${{ steps.syft.outputs.cmd }} -o json dir:. > syfttmp.json

      - name: Upload Syft Summary
        uses: actions/upload-artifact@v4.3.1
        with:
          name: syft_summary
          path: syfttmp.json

  ## Crée le index.html pour visualiser les failles possibles        
  Upload-index:
    name: Upload index
    needs: [Run-Grype,Run-Syft]
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses : actions/checkout@v4

      - name: Retrieving Grype Summary
        uses: actions/download-artifact@v4.1.4
        with:
          name: grype_summary
      
      - name: Retrieving Syft Summary
        uses: actions/download-artifact@v4.1.4
        with:
          name: syft_summary

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'

      - name: Exec python scrypt
        run: python ./.github/workflows/generate_html.py > index.html

      - name: Archive index as Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: artifact_index
          path: ./index.html

  ## Crée le dépendance.html pour visualiser les failles trouvé par grype:
  Upload-Dep:
    name: Upload Dep
    needs: [Run-Grype,Run-Syft]
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses : actions/checkout@v4

      - name: Retrieving Grype Summary
        uses: actions/download-artifact@v4.1.4
        with:
          name: grype_summary

      - name: Retrieving Syft Summary
        uses: actions/download-artifact@v4.1.4
        with:
          name: syft_summary

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'
      
      - name: Exec python scrypt
        run: python ./.github/workflows/generate_list_html.py > dependance.html

      - name: Archive Dependance as Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: artifact_dependance
          path: ./dependance.html

  Upload-Artifact:
    name: Retireve and upload artifact
    needs: [Upload-index,Upload-Dep]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Retrieving index artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: artifact_index
      
      - name: Retrieving Dependance artifact
        uses: actions/download-artifact@v4.1.4
        with:
          name: artifact_dependance
      
      - name: copy home.png
        run: cp ./.github/workflows/home.png ./home.png

      - name: Archives index and dependance in the same artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: vulnerabilities.zip
          path: |
            ./index.html
            ./dependance.html
            ./home.png

  ## Retire les artefacts temporaires
  Remove-Artifact:
    name: Remove Artifact
    needs: Upload-Artifact
    runs-on: ubuntu-latest

    steps:
      - name : Checkout
        uses : actions/checkout@v4

      - name: Retrieving Grype Summary
        uses: actions/download-artifact@v4.1.4
        with:
          name: grype_summary
      
      - name: Retrieving Syft Summary
        uses: actions/download-artifact@v4.1.4
        with:
          name: syft_summary
      
      - name : Delete TMP artifacts
        uses: geekyeggo/delete-artifact@v5.0.0
        with:
          name: |
            *_summary
            artifact_*
      
      