name: Check Vulnerabilities

on:
  push:
    branches:
      - main
      - SummaryDependancies
  workflow_dispatch:

jobs:
  run-syft:
    name: Grype Checkout
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v2
      
      - name: spdx
        uses: anchore/sbom-action@v0.12.0
        with:
          format: spdf-json
          artifact-name: spdx-json.json
        
      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
          path: .
