name: Check Vulnerabilities

on:
  push:
    branches:
      - main
      - SummaryDependancies
  workflow_dispatch:

jobs:
  run-test:
    name: Vulnerabilities Checkout
    runs-on: ubuntu-latest
    container:
      image: anchore/grype:latest
      volumes:
        - ${{ github.workspace }}:/app 
    steps:
      - name: Scan current project
        uses: anchore/scan-action@v3
        with:
          path: "."
