name: Check Vulnerabilities

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-syft:
    name: Grype Checkout
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v2.4.2
      
      - name: Scan
        uses: anchore/scan-action@v3
        with:
          path: .
          fail-build: false
          output-format: json