name: Check Vulnerabilities

on:
  push:
    branches:
      - main
      - SummaryDependancies
  workflow_dispatch:

jobs:
  run-syft:
    name: Syft Checkout
    runs-on: ubuntu-latest
    steps:
      - name : checkout
        uses : actions/checkout@v2
        
      - name: Scan current project
        uses: anchore/sbom-action@v0.12.0
