name: Check Vulnerabilities

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-syft:
    name: Grype Checkout
    runs-on: ubuntu-latest
    steps:
      - name : Checkout
        uses : actions/checkout@v2.4.2

      - name: Scan and Store
        uses: anchore/scan-action/download-grype@v3
        id: grype

      - run: ${{steps.grype.outputs.cmd}} dir:. > tmp
      
      - name: View Scan
        run: cat tmp
